# Generated by Django 3.2.6 on 2021-08-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_options'),
        ('news', '0004_articlecomment'),
    ]

    operations = [
    ]
